name: Update TZ submodule

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout and update submodules
        id: update_tz
        shell: sh
        run: .github/bin/update-tz.sh
      - name: Create Pull Request
        uses: quodlibetor/pull-request-action@1.0.6-patch1
        if: ${{ steps.update_tz.outputs.did_update == 'yes' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: main
          FAIL_ON_ERROR: 'yes'
